// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: proto/partitioning.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartitionLookupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *PartitionLookupRequest) Reset() {
	*x = PartitionLookupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_partitioning_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartitionLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionLookupRequest) ProtoMessage() {}

func (x *PartitionLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partitioning_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionLookupRequest.ProtoReflect.Descriptor instead.
func (*PartitionLookupRequest) Descriptor() ([]byte, []int) {
	return file_proto_partitioning_proto_rawDescGZIP(), []int{0}
}

func (x *PartitionLookupRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PartitionLookupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewrittenKey   string `protobuf:"bytes,1,opt,name=rewritten_key,json=rewrittenKey,proto3" json:"rewritten_key,omitempty"`
	ReplicaGroupId uint64 `protobuf:"varint,2,opt,name=replica_group_id,json=replicaGroupId,proto3" json:"replica_group_id,omitempty"`
}

func (x *PartitionLookupReply) Reset() {
	*x = PartitionLookupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_partitioning_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartitionLookupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionLookupReply) ProtoMessage() {}

func (x *PartitionLookupReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partitioning_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionLookupReply.ProtoReflect.Descriptor instead.
func (*PartitionLookupReply) Descriptor() ([]byte, []int) {
	return file_proto_partitioning_proto_rawDescGZIP(), []int{1}
}

func (x *PartitionLookupReply) GetRewrittenKey() string {
	if x != nil {
		return x.RewrittenKey
	}
	return ""
}

func (x *PartitionLookupReply) GetReplicaGroupId() uint64 {
	if x != nil {
		return x.ReplicaGroupId
	}
	return 0
}

type RegisterReplicaGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Members []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *RegisterReplicaGroupRequest) Reset() {
	*x = RegisterReplicaGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_partitioning_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReplicaGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReplicaGroupRequest) ProtoMessage() {}

func (x *RegisterReplicaGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partitioning_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReplicaGroupRequest.ProtoReflect.Descriptor instead.
func (*RegisterReplicaGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_partitioning_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReplicaGroupRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterReplicaGroupRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type RegisterReplicaGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterReplicaGroupReply) Reset() {
	*x = RegisterReplicaGroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_partitioning_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReplicaGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReplicaGroupReply) ProtoMessage() {}

func (x *RegisterReplicaGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partitioning_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReplicaGroupReply.ProtoReflect.Descriptor instead.
func (*RegisterReplicaGroupReply) Descriptor() ([]byte, []int) {
	return file_proto_partitioning_proto_rawDescGZIP(), []int{3}
}

type UnregisterReplicaGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UnregisterReplicaGroupRequest) Reset() {
	*x = UnregisterReplicaGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_partitioning_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterReplicaGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterReplicaGroupRequest) ProtoMessage() {}

func (x *UnregisterReplicaGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partitioning_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterReplicaGroupRequest.ProtoReflect.Descriptor instead.
func (*UnregisterReplicaGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_partitioning_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterReplicaGroupRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UnregisterReplicaGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnregisterReplicaGroupReply) Reset() {
	*x = UnregisterReplicaGroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_partitioning_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterReplicaGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterReplicaGroupReply) ProtoMessage() {}

func (x *UnregisterReplicaGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partitioning_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterReplicaGroupReply.ProtoReflect.Descriptor instead.
func (*UnregisterReplicaGroupReply) Descriptor() ([]byte, []int) {
	return file_proto_partitioning_proto_rawDescGZIP(), []int{5}
}

var File_proto_partitioning_proto protoreflect.FileDescriptor

var file_proto_partitioning_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2a, 0x0a, 0x16, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x65, 0x0a,
	0x14, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x77, 0x72, 0x69, 0x74, 0x74,
	0x65, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x77, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x1b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x1b, 0x0a,
	0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2f, 0x0a, 0x1d, 0x55, 0x6e,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x55,
	0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x9b, 0x02, 0x0a, 0x0b, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x06, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x5e, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x64, 0x0a, 0x16, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x24, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x6e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x6d, 0x6f, 0x64, 0x69,
	0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_partitioning_proto_rawDescOnce sync.Once
	file_proto_partitioning_proto_rawDescData = file_proto_partitioning_proto_rawDesc
)

func file_proto_partitioning_proto_rawDescGZIP() []byte {
	file_proto_partitioning_proto_rawDescOnce.Do(func() {
		file_proto_partitioning_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_partitioning_proto_rawDescData)
	})
	return file_proto_partitioning_proto_rawDescData
}

var file_proto_partitioning_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_partitioning_proto_goTypes = []interface{}{
	(*PartitionLookupRequest)(nil),        // 0: proto.PartitionLookupRequest
	(*PartitionLookupReply)(nil),          // 1: proto.PartitionLookupReply
	(*RegisterReplicaGroupRequest)(nil),   // 2: proto.RegisterReplicaGroupRequest
	(*RegisterReplicaGroupReply)(nil),     // 3: proto.RegisterReplicaGroupReply
	(*UnregisterReplicaGroupRequest)(nil), // 4: proto.UnregisterReplicaGroupRequest
	(*UnregisterReplicaGroupReply)(nil),   // 5: proto.UnregisterReplicaGroupReply
}
var file_proto_partitioning_proto_depIdxs = []int32{
	0, // 0: proto.Partitioner.Lookup:input_type -> proto.PartitionLookupRequest
	2, // 1: proto.Partitioner.RegisterReplicaGroup:input_type -> proto.RegisterReplicaGroupRequest
	4, // 2: proto.Partitioner.UnregisterReplicaGroup:input_type -> proto.UnregisterReplicaGroupRequest
	1, // 3: proto.Partitioner.Lookup:output_type -> proto.PartitionLookupReply
	3, // 4: proto.Partitioner.RegisterReplicaGroup:output_type -> proto.RegisterReplicaGroupReply
	5, // 5: proto.Partitioner.UnregisterReplicaGroup:output_type -> proto.UnregisterReplicaGroupReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_partitioning_proto_init() }
func file_proto_partitioning_proto_init() {
	if File_proto_partitioning_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_partitioning_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartitionLookupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_partitioning_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartitionLookupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_partitioning_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReplicaGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_partitioning_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReplicaGroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_partitioning_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterReplicaGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_partitioning_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterReplicaGroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_partitioning_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_partitioning_proto_goTypes,
		DependencyIndexes: file_proto_partitioning_proto_depIdxs,
		MessageInfos:      file_proto_partitioning_proto_msgTypes,
	}.Build()
	File_proto_partitioning_proto = out.File
	file_proto_partitioning_proto_rawDesc = nil
	file_proto_partitioning_proto_goTypes = nil
	file_proto_partitioning_proto_depIdxs = nil
}
