// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: proto/routing.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteLookupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RouteLookupRequest) Reset() {
	*x = RouteLookupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_routing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteLookupRequest) ProtoMessage() {}

func (x *RouteLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteLookupRequest.ProtoReflect.Descriptor instead.
func (*RouteLookupRequest) Descriptor() ([]byte, []int) {
	return file_proto_routing_proto_rawDescGZIP(), []int{0}
}

func (x *RouteLookupRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RouteLookupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addrs []string `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *RouteLookupReply) Reset() {
	*x = RouteLookupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_routing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteLookupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteLookupReply) ProtoMessage() {}

func (x *RouteLookupReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteLookupReply.ProtoReflect.Descriptor instead.
func (*RouteLookupReply) Descriptor() ([]byte, []int) {
	return file_proto_routing_proto_rawDescGZIP(), []int{1}
}

func (x *RouteLookupReply) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type RoutePublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *RoutePublishRequest) Reset() {
	*x = RoutePublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_routing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutePublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePublishRequest) ProtoMessage() {}

func (x *RoutePublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePublishRequest.ProtoReflect.Descriptor instead.
func (*RoutePublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_routing_proto_rawDescGZIP(), []int{2}
}

func (x *RoutePublishRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoutePublishRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type RoutePublishReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoutePublishReply) Reset() {
	*x = RoutePublishReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_routing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutePublishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePublishReply) ProtoMessage() {}

func (x *RoutePublishReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePublishReply.ProtoReflect.Descriptor instead.
func (*RoutePublishReply) Descriptor() ([]byte, []int) {
	return file_proto_routing_proto_rawDescGZIP(), []int{3}
}

type RouteUnpublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *RouteUnpublishRequest) Reset() {
	*x = RouteUnpublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_routing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteUnpublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUnpublishRequest) ProtoMessage() {}

func (x *RouteUnpublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUnpublishRequest.ProtoReflect.Descriptor instead.
func (*RouteUnpublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_routing_proto_rawDescGZIP(), []int{4}
}

func (x *RouteUnpublishRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RouteUnpublishRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type RouteUnpublishReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RouteUnpublishReply) Reset() {
	*x = RouteUnpublishReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_routing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteUnpublishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUnpublishReply) ProtoMessage() {}

func (x *RouteUnpublishReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUnpublishReply.ProtoReflect.Descriptor instead.
func (*RouteUnpublishReply) Descriptor() ([]byte, []int) {
	return file_proto_routing_proto_rawDescGZIP(), []int{5}
}

var File_proto_routing_proto protoreflect.FileDescriptor

var file_proto_routing_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x12,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x28, 0x0a, 0x10, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x22, 0x39, 0x0a, 0x13,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3b, 0x0a, 0x15,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x32, 0xd4, 0x01, 0x0a, 0x06, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x06, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x07, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x47,
	0x0a, 0x09, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x73,
	0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_routing_proto_rawDescOnce sync.Once
	file_proto_routing_proto_rawDescData = file_proto_routing_proto_rawDesc
)

func file_proto_routing_proto_rawDescGZIP() []byte {
	file_proto_routing_proto_rawDescOnce.Do(func() {
		file_proto_routing_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_routing_proto_rawDescData)
	})
	return file_proto_routing_proto_rawDescData
}

var file_proto_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_routing_proto_goTypes = []interface{}{
	(*RouteLookupRequest)(nil),    // 0: proto.RouteLookupRequest
	(*RouteLookupReply)(nil),      // 1: proto.RouteLookupReply
	(*RoutePublishRequest)(nil),   // 2: proto.RoutePublishRequest
	(*RoutePublishReply)(nil),     // 3: proto.RoutePublishReply
	(*RouteUnpublishRequest)(nil), // 4: proto.RouteUnpublishRequest
	(*RouteUnpublishReply)(nil),   // 5: proto.RouteUnpublishReply
}
var file_proto_routing_proto_depIdxs = []int32{
	0, // 0: proto.Router.Lookup:input_type -> proto.RouteLookupRequest
	2, // 1: proto.Router.Publish:input_type -> proto.RoutePublishRequest
	4, // 2: proto.Router.Unpublish:input_type -> proto.RouteUnpublishRequest
	1, // 3: proto.Router.Lookup:output_type -> proto.RouteLookupReply
	3, // 4: proto.Router.Publish:output_type -> proto.RoutePublishReply
	5, // 5: proto.Router.Unpublish:output_type -> proto.RouteUnpublishReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_routing_proto_init() }
func file_proto_routing_proto_init() {
	if File_proto_routing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_routing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteLookupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_routing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteLookupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_routing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutePublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_routing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutePublishReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_routing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteUnpublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_routing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteUnpublishReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_routing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_routing_proto_goTypes,
		DependencyIndexes: file_proto_routing_proto_depIdxs,
		MessageInfos:      file_proto_routing_proto_msgTypes,
	}.Build()
	File_proto_routing_proto = out.File
	file_proto_routing_proto_rawDesc = nil
	file_proto_routing_proto_goTypes = nil
	file_proto_routing_proto_depIdxs = nil
}
